version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly"  # 주간 업데이트
    open-pull-requests-limit: 5  # 최대 5개의 풀 리퀘스트만 열기
    assignees:
      - "kadragon"
    target-branch: "main"
